### ISSUE TITLE
Module.json needs updating?

### ISSUE THREAD

**Issue by DuskyVoltage** [MarkPearce/marks-headshot-remake#1]
I'm trying to install this module and getting the following error in the console:

> setup.js:292 Error: Unable to load valid module manifest data from "https://github.com/MarkPearce/marks-headshot-remake/releases/latest/download/module.json"
Module Model Validation Errors
[Module.packs]: Model Validation Errors
The Compendium pack "marks-headshot-actors" of the "Actor" type must declare the "system" upon which it depends.
    at Module.installPackage (file:///D:/Program%20Files/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1620)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///D:/Program%20Files/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)

![error](https://user-images.githubusercontent.com/9156437/196975629-6599ed2c-b8b3-48ed-99ae-53b2f360de16.png)

I saw your trailer and this looks really awesome, I'd love to run it!

**Comment by MarkPearce** [comment]
Are you running foundry V10?

Seems I may need to update the manifest format….

**Comment by DuskyVoltage** [comment]
D'oh, I should've said - Yeah, I'm on v10.
